change terraform workspace name

diff --git a/.github/workflows/terraform-plan-apply.yml b/.github/workflows/terraform-plan-apply.yml
--- a/.github/workflows/terraform-plan-apply.yml
+++ b/.github/workflows/terraform-plan-apply.yml
@@ -63,20 +63,19 @@ jobs:
             echo "current definition file path: $path"
 
             # Extract values for the trial
-            trialName=$(jq -r '.name' ./$path)
-            trialId=$(jq -r '.id' ./$path)
+            trial_name=$(jq -r '.name' ./$path)
             trial_dir=$(dirname $(realpath $path))
 
             # Check that trial name in the json equals to its folder name.
             last_dir_name=$(basename $trial_dir)
-            if [[ "$last_dir_name" != "$trialName" ]]
+            if [[ "$last_dir_name" != "$trial_name" ]]
             then
-              echo "ERROR: trial name (${trialName}) is not equal to its folder (${last_dir_name})." >&2
+              echo "ERROR: trial name (${trial_name}) is not equal to its folder (${last_dir_name})." >&2
               exit 1
             fi
 
             # Prepare the matrix item
-            MatrixItem="{\"trial_id\": \"$trialId\", \"path\": \"$path\", \"trial_name\": \"$trialName\", \"trial_dir\": \"$trial_dir\",},"
+            MatrixItem="{\"trial_name\": \"$trial_name\", \"trial_dir\": \"$trial_dir\",},"
 
             JSON="$JSON$MatrixItem"
           done <<< "$FILES"
@@ -92,7 +91,7 @@ jobs:
           echo "::set-output name=matrix::$( echo "$JSON" )"
 
   deploy:
-    name: "Execute TF on ${{ matrix.trial_name }}: ${{ matrix.path }}"
+    name: "Execute Terraform"
     needs: prepare-run-matrix
     if: ${{ needs.prepare-run-matrix.outputs.is_empty_matrix == 'false' }}
     strategy:
@@ -119,12 +118,21 @@ jobs:
         run: terraform init
 
       - name: Terraform workspace
-        run: terraform workspace select ${{ matrix.trial_id }} || terraform workspace new ${{ matrix.trial_id }}
+        run: |
+          set -o errexit
+          set -o pipefail
+          set -o nounset
+          # set -o xtrace
+
+          # github ref comes with "/" which is not valid for workspace names
+          ref_for_workspace="${GITHUB_REF//\//_}"
+          workspace_name="${{ matrix.trial_name }}-${ref_for_workspace}"
+          terraform workspace select ${workspace_name} || terraform workspace new ${workspace_name}
 
       - name: Terraform Format
         run: terraform fmt -check
 
-      - name: Prepare tfvars file
+      - name: Prepare deployment variables
         env:
           TFVARS_TEMPLATE: 'tfvars.template'
         run: |
@@ -162,27 +170,33 @@ jobs:
 
           cat ${{ matrix.trial_name }}.tfvars
 
+          # extract more values from the definition file
+          echo "tenant_id=$(jq -r '.tenant_id' ${definition_path})" >> $GITHUB_ENV
+          echo "ui_client_id=$(jq -r '.ui_client_id' ${definition_path})" >> $GITHUB_ENV
+
       # Plan TF
-      - name: Plan TF for "${{ matrix.trial_name }}"
+      - name: Terraform plan
         run: |
           set -o errexit
           set -o pipefail
           set -o nounset
           # set -o xtrace
 
-          terraform plan -var-file=${{ matrix.trial_name }}.tfvars -var="owner=${{ github.actor }}"
+          terraform plan -out=tfplan -var-file=${{ matrix.trial_name }}.tfvars \
+            -var="owner=${{ github.actor }}" \
+            -var="github_ref=${{ github.ref }}"
 
       # Apply, only on merge to main
-      - name: Apply TF for "${{ matrix.trial_name }}"
+      - name: Terraform apply
         # if: github.ref == 'refs/heads/main'
         run: |
           set -o errexit
           set -o pipefail
           set -o nounset
-          # set -o xtrace
+          set -o xtrace
 
           echo "Merged to main. applying trial's RG"
-          terraform apply -var-file=${{ matrix.trial_name }}.tfvars -var="owner=${{ github.actor }}" -auto-approve
+          terraform apply -auto-approve tfplan
 
           # '-raw' is important so no other characters will be added
           ui_storage_conn_string=$(terraform output -raw ui_conn_string)
@@ -190,16 +204,6 @@ jobs:
           # create an env var from the connection string, so will be available for the later steps
           echo "ui_storage_conn_string=$ui_storage_conn_string" >> $GITHUB_ENV
           echo "gateway_host_string=$gateway_host_string" >> $GITHUB_ENV
-
-          echo "trial_path=${{ matrix.trial_dir }}" >> $GITHUB_ENV
-          echo "trial_name=${{ matrix.trial_name }}" >> $GITHUB_ENV
-          echo "tenant_id=${{ matrix.tenant_id }}" >> $GITHUB_ENV
-          echo "ui_client_id=${{ matrix.ui_client_id }}" >> $GITHUB_ENV
-
-          # extract more values from the definition file
-          definition_path=${{ matrix.trial_dir }}/definition.json
-          echo "tenant_id=$(jq -r '.tenant_id' ${definition_path})" >> $GITHUB_ENV
-          echo "ui_client_id=$(jq -r '.ui_client_id' ${definition_path})" >> $GITHUB_ENV
 
           ## DO NOT DELETE ##
           # mask this value so this sensitive data won't be logged.
@@ -219,12 +223,12 @@ jobs:
           set -o errexit
           set -o pipefail
           set -o nounset
-          set -o xtrace
+          # set -o xtrace
 
           unzip mts-trial-ui.zip
 
           index_file="mts-trial-ui/index.html"
-          # sed doesn't like the github {{ }} vars, so droping the value to a regular var
+          # sed doesn't like the github {{ }} vars, so dropping the value to a regular var
           trial_name=${{ matrix.trial_name }}
 
           sed -i "s/{{clientId}}/${ui_client_id}/" ${index_file}
@@ -250,7 +254,7 @@ jobs:
           set -o errexit
           set -o pipefail
           set -o nounset
-          set -o xtrace
+          # set -o xtrace
 
           # first clean up the container, then upload the new assets
           az storage blob delete-batch --connection-string ${ui_storage_conn_string} --source "\$web" --pattern "*"
@@ -258,7 +262,7 @@ jobs:
 
   deployall:
     runs-on: ubuntu-latest
-    name: TF plan/apply (matrix)
+    name: Terraform plan/apply (matrix)
     needs: deploy
     steps:
       - name: Check TF (plan) matrix status
